### ISSUE TITLE
Add SubWallet to the list of Wallets in the Polkadot ecosystem

### ISSUE THREAD

**Issue by djhatrang** [shawntabrizi/awesome-polkadot#2]
I'm requesting the addition of SubWallet to the Wallet list. Below is some information about SubWallet:
- The most comprehensive wallet with a consistent UI and UX available on 3 platforms: browser extension, mobile app, and web dashboard.
- The most highly adopted wallet, with 1.6M+ downloads and 800K+ active users and devices.
- The most comprehensive earning solution that integrates direct nomination, nomination pools, parachain staking, and liquid staking. 
- In-app swap that integrates providers including Chainflip, Hydration, Asset Hub Swap

Let me know what other info you need.

Cheers,

**Comment by shawntabrizi** [comment]
Hi @djhatrang.

I appreciate your pull request, and also the SubWallet team.

As noted in my document, the list is not meant to be exhaustive, but instead represent the tools I use.

I currently use Nova wallet, and have not tried SubWallet, so that is the product I would like to represent here.

I strongly encourage you to recommend that people in your community also create their own `awesome-polkadot` repo, with the tools and wallets they use, and then you can get SubWallet correctly represented.

I hope you understand, thanks!
